version: '3'

services:
  python:
    image: ghcr.io/unplus/python:${PYTHON_VERSION}
    build:
      context: .
      dockerfile: Dockerfile.python
      args:
        PYTHON_VERSION: ${PYTHON_VERSION}

  poetry:
    image: ghcr.io/unplus/poetry:${POETRY_VERSION}-py${PYTHON_VERSION}
    build:
      context: .
      dockerfile: Dockerfile.poetry
      args:
        PYTHON_VERSION: ${PYTHON_VERSION}
        POETRY_VERSION: ${POETRY_VERSION}
