name: Publish Docker image
on:
  push:
    tags:
      - v*
jobs:
  build:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Define version
        run: |
          echo "POETRY_VERSION=$(echo '${{ toJSON(github) }}' | jq -r 'select(has("ref")) | .ref[11:] | split("-") | .[0]')" >> $GITHUB_ENV
          echo "PYTHON_VERSION=$(echo '${{ toJSON(github) }}' | jq -r 'select(has("ref")) | .ref[11:] | split("-") | .[1]')" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push of Python
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.python
          build-args: PYTHON_VERSION=${{ env.PYTHON_VERSION }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/unplus/python:${{ env.PYTHON_VERSION }}

      - name: Build and push of Poetry
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.poetry
          build-args: PYTHON_VERSION=${{ env.PYTHON_VERSION }},POETRY_VERSION=${{ env.POETRY_VERSION }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/unplus/poetry:${{ env.POETRY_VERSION }}-py${{ env.PYTHON_VERSION }}
