name: Publish Docker image
on:
  push:
    branches:
      - dev
jobs:
  build:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest

      - name: Build and Publish
        run: |
          docker buildx build \
            --push \
            --platform linux/amd64,linux/arm64/v8 \
            --file Dockerfile.python \
            --build-arg PYTHON_VERSION=3.9.8 \
            -t ghcr.io/unplus/python:3.9.8 .
